"""Build the shared stylesheet and sync the shared chrome into every page.

    python tools/build.py           # css/core.css, then head + header + footer from partials/, ?v=N on assets
    python tools/build.py --bump    # the same, after raising V by one (do this after any CSS/JS change)
    python tools/build.py --check   # also report links and files that do not exist

css/core.css is generated: it joins the six shared stylesheets (CORE, in cascade
order) into one request. Edit those files, never core.css. Page stylesheets
(css/home.css, css/article.css, ...) are linked as they are.

partials/head.html, partials/header.html and partials/footer.html are the source of
truth. Each page keeps a copy between <!-- tot:NAME --> and <!-- /tot:NAME -->;
never edit the copy inside a page. Links that point at the page itself get
aria-current="page". No dependencies: standard-library Python 3.8+.
"""
import os
import re
import sys

V = 2                 # asset version, written as ?v=N on every css/ and js/ reference
BASE_404 = '/theme-times-of-palestine/'   # where the site is served from: '/' at a domain root, '/<repository>/' on a GitHub project site

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTIALS = ('head', 'header', 'footer')
CORE = ('fonts', 'tokens', 'base', 'components', 'header', 'footer')   # css/<name>.css -> css/core.css


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def write(path, text):
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def bump():
    global V
    me = os.path.abspath(__file__)
    src = read(me)
    V += 1
    write(me, re.sub(r'^V = \d+', f'V = {V}', src, count=1, flags=re.M))


def minify(css):
    """Comments out, whitespace collapsed; spaces kept wherever they can carry meaning
    (selectors such as ':where(.tot) :focus-visible', calc(), strings)."""
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    css = re.sub(r'\s+', ' ', css)
    css = re.sub(r'\s*([{};,])\s*', r'\1', css)
    return css.replace(';}', '}').strip()


def bundle():
    parts = [f'/* {name}.css */' + minify(read(os.path.join(ROOT, 'css', name + '.css'))) for name in CORE]
    banner = '/* core.css: generated by tools/build.py from ' + ', '.join(f'{n}.css' for n in CORE) + '. Edit those files, not this one. */\n'
    write(os.path.join(ROOT, 'css', 'core.css'), banner + '\n'.join(parts) + '\n')


def mark_current(html, page):
    """aria-current="page" on links to this very page (no query, no fragment)."""
    html = html.replace(' aria-current="page"', '')
    return re.sub(r'<a ([^>]*?)href="' + re.escape(page) + r'"', r'<a \1href="' + page + r'" aria-current="page"', html)


def insert(html, name, partial, page):
    pattern = re.compile(r'([ \t]*)<!-- tot:' + name + r' -->\n.*?\n[ \t]*<!-- /tot:' + name + ' -->', re.S)
    match = pattern.search(html)
    if not match:
        return html, False
    pad = match.group(1)
    body = '\n'.join((pad + line) if line else line for line in partial.strip('\n').split('\n'))
    if name != 'head':
        body = mark_current(body, page)
    block = f'{pad}<!-- tot:{name} -->\n{body}\n{pad}<!-- /tot:{name} -->'
    return html[:match.start()] + block + html[match.end():], True


def versions(html):
    return re.sub(r'((?:css|js)/[\w./-]+\.(?:css|js))\?v=\d+', rf'\1?v={V}', html)


SKIP = ('#', 'http:', 'https:', 'mailto:', 'tel:', 'data:', '//', '/', '?', 'javascript:')


def _rebase(url, add, base):
    if add:
        return url if url.startswith(SKIP) else base + url
    return url[len(base):] if url.startswith(base) else url


def rebase(html, base, add=True):
    """404.html is served at any depth on static hosts, so its URLs must be root-relative."""
    def attr(m):
        name, value = m.group(1), m.group(2)
        if name == 'srcset':
            parts = [p.strip().split(' ', 1) for p in value.split(',')]
            value = ', '.join(' '.join([_rebase(p[0], add, base)] + p[1:]) for p in parts)
        else:
            value = _rebase(value, add, base)
        return f'{name}="{value}"'
    return re.sub(r'\b(href|src|srcset|action)="([^"]*)"', attr, html)


def check(pages):
    problems, placeholders = [], set()
    for page in pages:
        html = read(os.path.join(ROOT, page))
        ids = re.findall(r'\sid="([^"]+)"', html)
        problems += [f'{page}: duplicate id "{i}"' for i in sorted(set(ids)) if ids.count(i) > 1]
        refs = re.findall(r'\b(?:href|src|action)="([^"#?]+)', html)
        refs += [u.strip().split(' ')[0] for s in re.findall(r'srcset="([^"]+)"', html) for u in s.split(',')]
        for ref in sorted(set(refs)):
            if page == '404.html' and ref.startswith(BASE_404):
                path = ref[len(BASE_404):]
            elif ref.startswith(SKIP):
                continue
            else:
                path = ref
            if path and not os.path.exists(os.path.join(ROOT, path)):
                problems.append(f'{page}: missing {ref}')
        placeholders |= {f for f in re.findall(r'href="#([\w-]+)"', html) if f not in ids}
    if placeholders:
        problems.append('placeholder links (no target yet): #' + ', #'.join(sorted(placeholders)))
    return problems


def main():
    if '--bump' in sys.argv:
        bump()
    bundle()
    partials ={name: read(os.path.join(ROOT, 'partials', name + '.html')) for name in PARTIALS}
    pages = sorted(f for f in os.listdir(ROOT) if f.endswith('.html'))
    for page in pages:
        path = os.path.join(ROOT, page)
        html = read(path)
        marker = re.search(r'<!-- tot:base (\S+) -->', html)
        if page == '404.html' and marker:
            html = rebase(html, marker.group(1), add=False)
        found = []
        for name in PARTIALS:
            html, ok = insert(html, name, partials[name], page)
            if ok:
                found.append(name)
        html = versions(html)
        if page == '404.html':
            html = rebase(html, BASE_404)
            html = re.sub(r'<!-- tot:base \S+ -->', f'<!-- tot:base {BASE_404} -->', html) if marker else \
                html.replace('<head>', f'<head>\n<!-- tot:base {BASE_404} -->', 1)
        write(path, html)
        print(f'{page:18s} {", ".join(found) or "(no partials)"}')
    for name in PARTIALS:
        write(os.path.join(ROOT, 'partials', name + '.html'), versions(partials[name]))
    print(f'assets at ?v={V}')
    if '--check' in sys.argv:
        problems = check(pages)
        print('\n'.join(problems) if problems else 'check: no missing files or duplicate ids')


if __name__ == '__main__':
    main()
